customhost = "database-1.ccl1xmpotylf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tanwenjun-employee"
customregion = "us-east-1"
